[package]
name = "diecast-handlebars"
version = "0.1.0"
authors = ["Jorge Israel Peña <jorge.israel.p@gmail.com>"]

[dependencies]
typemap = "*"
handlebars = "*"
rustc-serialize = "*"

[dependencies.diecast]
path = "../diecast"
